"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_DJANGO_SECRET_KEY_FROM_ENV = os.environ.get("DJANGO_SECRET_KEY")
SECRET_KEY = _DJANGO_SECRET_KEY_FROM_ENV or "dev-only-insecure-key"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "0") == "1"

# A missed DJANGO_SECRET_KEY env var in production would silently sign
# sessions and CSRF tokens with the fallback key above, which is committed
# to the repo and therefore public. Guard against that specifically —
# check whether the env var was ABSENT, not whether the resulting value
# happens to equal the fallback string, so a deliberately-set env var that
# happens to match it is not treated as a code-level misconfiguration.
#
# This must not fire in the test environment: pytest-django/Django's test
# runner forces `settings.DEBUG = False` by mutating the settings object
# AFTER this module has already finished importing, so this check — which
# runs once, at import time, against whatever DEBUG/env this process was
# actually started with — never re-evaluates against that later override.
# In this repo's docker test environment DJANGO_DEBUG=1 is set via `.env`
# regardless, so DEBUG is already True here and the guard is a no-op.
if not DEBUG and not _DJANGO_SECRET_KEY_FROM_ENV:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY is not set and DEBUG is False. Refusing to start "
        "with the committed 'dev-only-insecure-key' fallback in anything "
        "that isn't local development — that key is public in the repo and "
        "would silently sign production sessions and CSRF tokens."
    )

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]


def _env_flag(name, default="0"):
    return os.environ.get(name, default) == "1"


def _env_list(name, default=""):
    return [v.strip() for v in os.environ.get(name, default).split(",") if v.strip()]


# Django rejects an unsafe-method request whose Origin is not listed here. In
# production the browser's Origin is https://tasky.tailwebs.com, which never
# matches a bare ALLOWED_HOSTS entry, so this must be set independently.
CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS")

# Behind Apache behind Cloudflare, the request reaches Django over plain http.
# Without this Django believes the connection is insecure and will refuse to
# set Secure cookies (and SECURE_SSL_REDIRECT would loop forever).
#
# Only trust the header when the deployment actually terminates TLS upstream —
# if Django were ever exposed directly, a client could forge the header and
# claim https on a plaintext connection.
if _env_flag("DJANGO_BEHIND_PROXY"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# USE_X_FORWARDED_HOST is deliberately NOT set, even behind a proxy.
#
# Every proxy in the chain *appends* to X-Forwarded-Host. In production the
# chain is two hops — the host Apache, then the container's Apache — so Django
# would receive "tasky.tailwebs.com, tasky.tailwebs.com" and reject it with
# 400 DisallowedHost, since a comma-joined value matches no ALLOWED_HOSTS entry.
# It fails only through the full chain: a single-hop request (the container
# healthcheck) sends one value and passes, which makes it look like the app is
# healthy while every browser gets a 400.
#
# It is also unnecessary. Both vhosts set ProxyPreserveHost On, so the original
# Host header survives untouched and Django's default HTTP_HOST is correct.
# Only turn this on for a proxy that rewrites Host instead of preserving it,
# and then only with exactly one such proxy in front.

# Cookies default to secure whenever DEBUG is off, so forgetting the flag fails
# closed rather than shipping session cookies over plaintext.
SESSION_COOKIE_SECURE = _env_flag("DJANGO_SECURE_COOKIES", "0" if DEBUG else "1")
CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

SECURE_SSL_REDIRECT = _env_flag("DJANGO_SECURE_SSL_REDIRECT")
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'boards',
    'projects',
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # The SPA shell lives in ui/index.html and is rendered by the catch-all
        # route in config/urls.py.
        'DIRS': [BASE_DIR / 'ui'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("MYSQL_DATABASE", "tasky"),
        "USER": os.environ.get("MYSQL_USER", "tasky"),
        "PASSWORD": os.environ.get("MYSQL_PASSWORD", ""),
        "HOST": os.environ.get("MYSQL_HOST", "127.0.0.1"),
        "PORT": os.environ.get("MYSQL_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        "TEST": {
            "CHARSET": "utf8mb4",
            "COLLATION": "utf8mb4_unicode_ci",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# The UI is plain HTML/CSS/JS with no build step, so the source directory is
# served directly. `collectstatic` gathers it alongside Django admin's assets.
#
# Assets live in ui/static/ rather than ui/ so that the SAME absolute path
# (/static/js/app.js) resolves both here and under VS Code's Live Server when
# it is rooted at ui/. See .vscode/settings.json.
STATICFILES_DIRS = [BASE_DIR / 'ui' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Attachment file storage — local filesystem, not an object store (see
# docs/superpowers/specs/2026-08-24-tasky-task-detail-ux-design.md). Never
# served directly: boards.views.AttachmentViewSet.download is the only
# path a client can fetch a file through, so it can enforce the same
# project-membership check every other endpoint does. No urls.py entry
# maps MEDIA_URL to a static-serving view — that's deliberate.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}

# ui/static/js/api.js reads this cookie to send the X-CSRFToken header, so it
# cannot be HttpOnly. The token is not a secret; the SameSite policy above is
# what stops a cross-site page from using it.
CSRF_COOKIE_HTTPONLY = False
