# Generated by Django 5.2.16 on 2026-08-21 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0019_backfill_work_item_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='new_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_items_with_status', to='boards.workitemstatus'),
        ),
    ]
