# Generated by Django 5.2.16 on 2026-08-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0024_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='work_items', to='boards.label'),
        ),
    ]
