# Generated by Django 5.2.16 on 2026-08-25 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0026_sprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='backlog_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workitem',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='boards.sprint'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['board', 'sprint', 'backlog_position'], name='boards_work_board_i_909874_idx'),
        ),
    ]
