# Generated by Django 5.2.16 on 2026-08-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0027_workitem_sprint_and_backlog_position'),
        ('projects', '0002_project_next_item_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('unreleased', 'Unreleased'), ('released', 'Released'), ('archived', 'Archived')], default='unreleased', max_length=10)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='projects.project')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('release_date'), nulls_last=True), 'name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='unique_release_name_per_project')],
            },
        ),
    ]
