# Generated by Django 5.2.16 on 2026-08-25 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0028_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='boards.release'),
        ),
    ]
