# Generated by Django 5.2.17 on 2026-09-16 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0031_automationrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='boards.comment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='work_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='boards.workitem'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('work_item__isnull', False)), models.Q(('comment__isnull', False), ('work_item__isnull', True)), _connector='OR'), name='attachment_exactly_one_parent'),
        ),
    ]
