# Generated by Django 5.2.17 on 2026-09-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0031_automationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
